import {
    AlertCircle,
    BarChart3,
    Calendar,
    CheckCircle2,
    ChevronsUpDown,
    Compass,
    CreditCard,
    Database,
    FileIcon,
    Flag,
    Folder,
    Globe,
    Home,
    Info,
    Link,
    Lock,
    MessageCircle,
    Moon,
    MoreHorizontal,
    PersonStanding,
    Plus,
    Settings,
    Shield,
    Smartphone,
    Sun,
    Trash,
    User,
    Wallet,
    X,
    Zap,
    ClipboardIcon,
    Pipelines,
    Chip,
    Category,
    Person,
} from "lucide-react";

export const icons = [
    { value: "chart", path: BarChart3 },
    { value: "headphone", path: MessageCircle },
    { value: "send", path: MessageCircle },
    { value: "pipelines", path: Flag },
    { value: "calendar", path: Calendar },
    { value: "settings", path: Settings },
    { value: "check", path: CheckCircle2 },
    { value: "chip", path: Zap },
    { value: "compass", path: Compass },
    { value: "database", path: Database },
    { value: "flag", path: Flag },
    { value: "home", path: Home },
    { value: "info", path: Info },
    { value: "link", path: Link },
    { value: "lock", path: Lock },
    { value: "messages", path: MessageCircle },
    { value: "notification", path: AlertCircle },
    { value: "payment", path: CreditCard },
    { value: "person", path: User },
    { value: "category", path: Folder },
    { value: "clipboardIcon", path: FileIcon },
    { value: "shield", path: Shield },
    { value: "warning", path: AlertCircle },
    { value: "wallet", path: Wallet },
    { value: "globe", path: Globe },
    { value: "zap", path: Zap },
];
